### ISSUE TITLE
  Will the code for this article ( "DNN-Chip Predictor") be open here?

### ISSUE THREAD

**Issue by wxbbuaa2011** [RICE-EIC/AutoDNNchip#2]
Your work is very good, and we really need your work to verify our idea. Thank you very munch. 
One more question, what's the difference between AutoDNNchip (predictor) and DNN-Chip Predictor?

**Comment by iso-p** [comment]
Thanks a lot! The repo here stick to a graph based description, and the method in the DNN chip predictor is for-loop based. The latter will be open sourced by my colleages in another git repo.

**Comment by iso-p** [comment]
Feel free to reach out to us if you have other questions.
