### ISSUE TITLE
issues about the result

### ISSUE THREAD

**Issue by Jupitor1** [RICE-EIC/AutoDNNchip#3]
Hi，Since I do n’t have an ultra 96 board now, can you tell me the number of optimized frames?
thanks a lot．

**Comment by iso-p** [comment]
Thanks! The results are tested on 1000 images: the baseline/optimized design can reach fps of 24.2/26.8 respectively.

**Comment by Jupitor1** [comment]
and under 220Mhz?

**Comment by iso-p** [comment]
yes.

**Comment by Jupitor1** [comment]
thanks
